PREFIX odml: <https://g-node.org/projects/odml-rdf#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#>


SELECT ?name ?mem
WHERE {
 ?data odml:hasValue ?sw .
 ?data odml:hasName ?name .
 ?sw rdfs:member ?mem 
  FILTER regex(?name, "Software")
  
}

