#get descriptions of all Resources

PREFIX crcns: <http://cz.zcu.kiv.data.crcns.xml#>
select  ?publisher ?val{
    ?descriptions crcns:descriptions ?description .
    ?descriptions crcns:publisher ?publisher.
    ?description crcns:description ?description1 .
    ?description1 crcns:value ?val .

}		
 





