#get formats by a filter

PREFIX crcns: <http://cz.zcu.kiv.data.crcns.json#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#>

select  ?type ?id ?label {
    ?data crcns:type ?type .
    ?data crcns:id ?id .
    ?data crcns:attributes ?attributes .
    ?attrubutes crcns:format ?format .
    ?format rdfs:member ?label FILTER regex(?label, "NIFTI")
    } 
 


